services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:5000"
    volumes:
      - .:/app
      - ./movies.json:/app/movies.json
    environment:
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5000 --reload

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
